version: "2"
services:
  connect:
    build: .
    #image: golang:alpine
    hostname: go
    container_name: go
    ports:
      - "8000:8000"
    volumes:
      - ./tests:/tests
      - ./webserver:/go/src/webserver
    environment:
      WEBSERVERPORT: "8000"
      UNIQUE_CD_CONNECT: 1
      #GOPATH: /go
      #PROGRAMA: sample_if.go
    working_dir: /tests
    command: > 
      sh -c "go get -u github.com/landoop/coyote &&
      coyote -c . &
      go run /go/src/webserver/main.go"

    # coyote -c ./tests &&

    # Update the build
    # docker build -t coyote_connect .

    # Run a folder of tests
    # coyote -c ./tests

    # Run test by test
    # coyote -c my-test.yml -c my-second-test.yml

    # The exit code of coyote is the number of failed tests, up to 254 failed tests

    # http://localhost:8000/coyote.html
